version: "3.7"
services:
    localstack:
        image: localstack/localstack:latest
        ports:
            - "4566-4599:4566-4599"
        environment:
            - AWS_DEFAULT_REGION=us-east-1
            - EDGE_PORT=4566
            - SERVICES=s3,sqs
        volumes:
            - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
            - "/var/run/docker.sock:/var/run/docker.sock"